# Informacion basica
title: "SynthBiont"
description: "Un blog de cositas varias."
baseurl: # Algo confuso pero aqui una explicacion: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
url: "https://synthbiont.com"
logo: "/images/synthbiont_logo.png"

# Tema
theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: es
date_format: "%B %-d, %Y" # Aca una explicacion de estas convenciones: http://strftime.net/ y https://strftime.org/

# Dar estimados de tiempo de lectura
read_time: true
words_per_minute: 200

# Formulas
mathjax:
  enable: true
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"

# Fuentes
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Pagination - https://jekyllrb.com/docs/pagination/
# Break up the main listing of posts on the home page across multiple pages by enabling pagination.
paginate: 10
paginate_path: /page:num/

# Search options
search_full_content: false # can have performance implications for large sites

# Disqus, twitter, GAnalytics
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: joangallego
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

# Collections
collections:
  recetas:
    output: true
    permalink: /:collection/:path/

# Liquid
# Liquid comes with a stricter parser that can be used when editing templates to give better error messages when templates are invalid. 
# strict = Raises a SyntaxError when invalid syntax is used
# other options are 'warn' and 'lax'
# https://github.com/Shopify/liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Taxonomy pages (for archive pages)
category_archive_path: "/categorias/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  # Recetas defaults
  - scope:
      path: "_recetas"
      type: recetas
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Joan
  picture:
  email: synthbiont@gmail.com
  twitter: joangallego
  links:
    - title: Twitter
      url: https://twitter.com/joangallego
      icon: fab fa-twitter-square
    - title: Spotify
      url: https://open.spotify.com/user/joan-gallego
      icon: fab fa-spotify

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/joangallego
    icon: fab fa-twitter-square
  - title: Spotify
    url: https://open.spotify.com/user/joan-gallego
    icon: fab fa-spotify
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
