site: SynthBiont
title: SynthBiont
description: >-
  Una nueva iteración de mi blog.
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Amsterdam
repo: https://github.com/synthbiont/synthbiont.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Joan
  bio: Una nueva iteración de mi blog.
  username: synthbiont # general username
  github: synthbiont # github username
  twitter: joangallego # twitter username
  email: synthbiont@riseup.net # email adress

# URL settings
url: "https://synthbiont.rocks" #
baseurl: "https://synthbiont.rocks" # leave blank if not wished
permalink: "https://synthbiont.rocks/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


